# Generated by Django 5.2.8 on 2025-11-08 05:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Homepage", "verbose_name_plural": "Homepages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 8),
                    ("stats_section", 11),
                    ("features_section", 14),
                    ("benefits_section", 17),
                    ("testimonials_section", 21),
                    ("pricing_section", 27),
                    ("cta_section", 28),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    3: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge_text", 0),
                                ("badge_icon", 0),
                                ("headline", 1),
                                ("description", 2),
                                ("primary_cta_text", 1),
                                ("primary_cta_link", 3),
                                ("secondary_cta_text", 4),
                                ("secondary_cta_link", 5),
                                ("hero_image", 6),
                                ("show_kpi_card", 7),
                                ("kpi_value", 4),
                                ("kpi_label", 4),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 1), ("label", 1)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: ("wagtail.blocks.StructBlock", [[("stats", 10)]], {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 1),
                                ("title", 1),
                                ("description", 2),
                                ("color_class", 1),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: ("wagtail.blocks.StructBlock", [[("features", 13)]], {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 1), ("title", 1), ("description", 2)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("benefits", 16),
                                ("image", 6),
                                ("headline", 1),
                                ("description", 2),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"max_value": 5, "min_value": 1, "required": True},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 1), ("role", 1), ("content", 2), ("rating", 18)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: ("wagtail.blocks.StructBlock", [[("testimonials", 20)]], {}),
                    22: ("wagtail.blocks.StructBlock", [[("text", 1)]], {}),
                    23: ("wagtail.blocks.ListBlock", (22,), {}),
                    24: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("price", 1),
                                ("features", 23),
                                ("cta_text", 1),
                                ("cta_link", 3),
                                ("highlight", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.ListBlock", (25,), {}),
                    27: ("wagtail.blocks.StructBlock", [[("pricing_plans", 26)]], {}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 1),
                                ("description", 2),
                                ("primary_cta_text", 1),
                                ("primary_cta_link", 3),
                                ("secondary_cta_text", 4),
                                ("secondary_cta_link", 5),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CTASection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("cta_text", models.CharField(max_length=50)),
                ("cta_link", models.URLField()),
                (
                    "landing_page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cta",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True, null=True)),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="hero_images/"),
                ),
                ("cta_text", models.CharField(blank=True, max_length=50, null=True)),
                ("cta_link", models.URLField(blank=True, null=True)),
                (
                    "landing_page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=50)),
                ("features", models.TextField()),
                ("most_popular", models.BooleanField(default=False)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField()),
                ("rating", models.IntegerField(default=5)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
    ]
